apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-sso-client-secret
  labels:
    app.kubernetes.io/part-of: argocd  
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: github-sso-client-secret
  data:
  - secretKey: "dex.github.clientSecret"
    remoteRef:
      key: kv/dex_github_clientSecret
      property: secret