config:
  namespace: internal

grafana:
  ingress:
    enabled: true	
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"      
    hosts:  
      - grafana.argouniverse.com
    tls:
      - secretName: issuer-letsencrypt-grafana
        hosts:
          - grafana.argouniverse.com      